Inmobi 10.0.9.0 Updates
InMobi/AppLovin-MAX-SDK-Android pull request #1
Opened 2022-08-11 06:52 UTC by manishk97

2022-08-11 07:35 UTC, sunilkuna5-inmobi commented on InMobi/src/main/java/com/applovin/mediation/adapters/InMobiMediationAdapter.java
>              listener.onNativeAdDisplayed( null );
AdImpressed is deprecated and should be removed

2022-08-11 11:31 UTC, venkinmobi approved these changes

2022-08-12 04:59 UTC, sunilkuna5-inmobi commented on InMobi/CHANGELOG.md
> +* Added Support for Publisher callback - onAdImpression
https://mvnrepository.com/artifact/com.applovin.mediation/inmobi-adapter/10.0.9.0
is already released.. you would need to raise changes to 10.0.9.1

2022-08-12 05:07 UTC, sunilkuna5-inmobi commented on InMobi/src/main/java/com/applovin/mediation/adapters/InMobiMediationAdapter.java
> +            log( "Rewarded Impressed" );
Log should be 
InMobi logged Impression successfully

2022-08-12 05:07 UTC, sunilkuna5-inmobi commented on InMobi/src/main/java/com/applovin/mediation/adapters/InMobiMediationAdapter.java
>              log( "Rewarded ad did show" );
This log should be removed or changed

2022-08-12 05:12 UTC, sunilkuna5-inmobi commented on InMobi/src/main/java/com/applovin/mediation/adapters/InMobiMediationAdapter.java
>              listener.onNativeAdDisplayed( null );
resolved

2022-08-12 05:13 UTC, sunilkuna5-inmobi requested changes
https://mvnrepository.com/artifact/com.applovin.mediation/inmobi-adapter/10.0.9.0
is already released.. you would need to raise changes to 10.0.9.1

2022-08-12 06:59 UTC, sunilkuna5-inmobi approved these changes

2022-08-16 05:39 UTC, merged